version: "3.9"

services:
  ## PostgreSQL ##############################################
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=poseidon
      - POSTGRES_USER=poseidonuser
      - POSTGRES_PASSWORD=poseidonpassword
    ports:
      - 5432:5432

